package report

import (
"fmt"
"time"
)

type Report struct {
Title       string
Description string
Findings    []Finding
StartTime   time.Time
EndTime     time.Time
}

func NewReport(title, description string) *Report {
return &Report{
Title:       title,
Description: description,
StartTime:   time.Now(),
}
}

func (r *Report) AddFinding(f Finding) {
r.Findings = append(r.Findings, f)
}

func (r *Report) GenerateMarkdown() string {
r.EndTime = time.Now()
var output string
output += "# " + r.Title + "\n\n"
output += "**Description:** " + r.Description + "\n\n"
output += "**Start Time:** " + r.StartTime.Format(time.RFC3339) + "\n"
output += "**End Time:** " + r.EndTime.Format(time.RFC3339) + "\n\n"
output += "## Findings\n\n"
for _, finding := range r.Findings {
output += "### " + finding.ID + ": " + finding.Title + "\n\n"
output += "**Severity:** " + finding.Severity + "\n\n"
output += "**Description:** " + finding.Description + "\n\n"
output += "**Evidence:** " + finding.Evidence + "\n\n"
output += "**Remediation:** " + finding.Remediation + "\n\n"
}
output += "---\n"
output += "*Generated by ANGEL C2 Framework*"
return output
}

func (r *Report) GenerateJSON() string {
return `{"title": "` + r.Title + `", "description": "` + r.Description + `", "findings": ` + fmt.Sprintf("%d", len(r.Findings)) + `}`
}

func (r *Report) Close() {
r.EndTime = time.Now()
}

func (r *Report) GetTotalFindings() int {
return len(r.Findings)
}
