package report

import (
"strconv"
"time"
)

type Severity string

const (
SeverityCritical Severity = "CRITICAL"
SeverityHigh     Severity = "HIGH"
SeverityMedium   Severity = "MEDIUM"
SeverityLow      Severity = "LOW"
)

type Finding struct {
ID          string
Title       string
Description string
Impact      string
Severity    Severity
Evidence    string
Remediation string
}

type Report struct {
Title       string
Description string
Findings    []Finding
StartTime   time.Time
EndTime     time.Time
}

func NewReport(title, description string) *Report {
return &Report{
Title:       title,
Description: description,
StartTime:   time.Now(),
}
}

func (r *Report) AddFinding(finding Finding) {
r.Findings = append(r.Findings, finding)
}

func (r *Report) GenerateMarkdown() string {
r.EndTime = time.Now()
var output string
output += "# " + r.Title + "\n\n"
output += "**Description:** " + r.Description + "\n\n"
output += "**Start Time:** " + r.StartTime.Format(time.RFC3339) + "\n"
output += "**End Time:** " + r.EndTime.Format(time.RFC3339) + "\n\n"
output += "## Findings\n\n"
for _, finding := range r.Findings {
output += "### " + finding.ID + ": " + finding.Title + "\n\n"
output += "**Severity:** " + string(finding.Severity) + "\n\n"
output += "**Description:** " + finding.Description + "\n\n"
output += "**Impact:** " + finding.Impact + "\n\n"
output += "**Evidence:** " + finding.Evidence + "\n\n"
output += "**Remediation:** " + finding.Remediation + "\n\n"
}
output += "---\n"
output += "*Generated by ANGEL C2 Framework*"
return output
}

func (r *Report) GenerateJSON() string {
return `{"title": "` + r.Title + `", "description": "` + r.Description + `", "start_time": "` + r.StartTime.Format(time.RFC3339) + `", "end_time": "` + r.EndTime.Format(time.RFC3339) + `", "findings": ` + strconv.Itoa(len(r.Findings)) + `}`
}

func (r *Report) GetSeverityStats() map[Severity]int {
stats := make(map[Severity]int)
for _, finding := range r.Findings {
stats[finding.Severity]++
}
return stats
}

func (r *Report) Close() {
r.EndTime = time.Now()
}

func (r *Report) GetTotalFindings() int {
return len(r.Findings)
}

func (r *Report) GetCriticalCount() int {
var count int
for _, finding := range r.Findings {
if finding.Severity == SeverityCritical {
count++
}
}
return count
}

func (r *Report) GetHighCount() int {
var count int
for _, finding := range r.Findings {
if finding.Severity == SeverityHigh {
count++
}
}
return count
}

func (r *Report) GetMediumCount() int {
var count int
for _, finding := range r.Findings {
if finding.Severity == SeverityMedium {
count++
}
}
return count
}

func (r *Report) GetLowCount() int {
var count int
for _, finding := range r.Findings {
if finding.Severity == SeverityLow {
count++
}
}
return count
}
