package report

import (
"time"
)

type TechnicalReport struct {
Title       string
Description string
Findings    []Finding
StartTime   time.Time
EndTime     time.Time
}

func NewTechnicalReport(title, description string) *TechnicalReport {
return &TechnicalReport{
Title:       title,
Description: description,
StartTime:   time.Now(),
}
}

func (t *TechnicalReport) AddFinding(finding Finding) {
t.Findings = append(t.Findings, finding)
}

func (t *TechnicalReport) GenerateMarkdown() string {
t.EndTime = time.Now()
var output string
output += "# " + t.Title + "\n\n"
output += "**Description:** " + t.Description + "\n\n"
output += "**Start Time:** " + t.StartTime.Format(time.RFC3339) + "\n"
output += "**End Time:** " + t.EndTime.Format(time.RFC3339) + "\n\n"
output += "## Findings\n\n"
for _, finding := range t.Findings {
output += "### " + finding.ID + ": " + finding.Title + "\n\n"
output += "**Severity:** " + finding.Severity + "\n\n"
output += "**Description:** " + finding.Description + "\n\n"
output += "**Evidence:** " + finding.Evidence + "\n\n"
output += "**Remediation:** " + finding.Remediation + "\n\n"
}
output += "---\n"
output += "*Generated by ANGEL C2 Framework*"
return output
}

func (t *TechnicalReport) GetFindings() []Finding {
return t.Findings
}

func (t *TechnicalReport) Close() {
t.EndTime = time.Now()
}
